spring:
  application:
    name: freezer_backend
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/freezer
    username: ${dbuser}
    password: ${dbpassword}
    driver-class-name: com.mysql.jdbc.Driver
    continue-on-error: true
  error:
    path: /error
